name: test
on: [push, pull_request]
jobs:
  test:
    uses: nimbase/setup-nim-action/.github/workflows/test.yml@main
    with:
      cache: 'false'
      nim-version: stable
      pre-test-command: 'sudo modprobe tls'