name: test
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - LICENSE
      - README.*
      - examples
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        nim-version:
          - 'stable'
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble install -Y
      - if: runner.os != 'Windows'
        run: nimble test -d:release
      - if: runner.os == 'Windows'
        shell: bash
        run: |
          nim c -r tests/test_http.nim
          nim c -r tests/test_net.nim
          nim c -r tests/test_security.nim
          nim c -r tests/test_signal.nim
